import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ThemeProvider } from "../context/ThemeContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="border-b bg-white">
          <nav className="mx-auto flex max-w-6xl items-center gap-6 px-6 py-4 text-sm">
            <Link href="/" className="font-medium text-[#0475bc] hover:text-[#005489]">
              <Image src="/logo.svg" alt="PORT" width={120} height={40} priority />
            </Link>
            <Link href="/predict-track" className="text-[#0475bc] hover:text-[#005489]">
              Predict & Track
            </Link>
            <Link href="/orchestrate-optimize" className="text-[#0475bc] hover:text-[#005489]">
              Orchestrate & Optimize
            </Link>
            <Link href="/resilience-response" className="text-[#0475bc] hover:text-[#005489]">
              Resilience & Response
            </Link>
            <Link
              href="/trade-empowerment-tailored-logistics"
              className="text-[#0475bc] hover:text-[#005489]"
            >
              Trade Empowerment & Tailored Logistics
            </Link>
          </nav>
        </header>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
